In [3]:
import numpy as np

In [4]:
a = np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [5]:
print(a[4])

9


In [6]:
print(a[0]) #first element of array

1


In [7]:
print(a[-2])

7


In [8]:
a = np.array([1,3,5,7,9])
print(a)
#slicing:
#array[start:stop:step]
#stop  - index , that  is not included in output

[1 3 5 7 9]


In [9]:
print(a[0:3]) #first 3 elemnts

[1 3 5]


In [10]:
print(a[-3:]) # last 3 elemnts

[5 7 9]


In [11]:
print(a[0::3])  # midle 3 elments with steps

[1 7]


In [12]:
print(a[0::2])

[1 5 9]


In [13]:
# indexing on 2 dimensional array 
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)
#2d array {row :column}
#2d array takes 2 value - row and column for indexing

[[1 2 3]
 [4 5 6]]


In [14]:
print(arr2[0])  # first row
print(arr2[1])  # second row


[1 2 3]
[4 5 6]


In [15]:
print(arr2[0][2])  # first row
print(arr2[1][2] ) # second row

3
6


In [17]:
print(arr2[1:])
print(arr2[:])

[[4 5 6]]
[[1 2 3]
 [4 5 6]]


In [19]:
print(arr2[-1])  # last element find 

[4 5 6]


In [20]:
print(arr2[1]) # specific elemnt -1d
print(arr2[1:]) # specific elemnt - 2d

[4 5 6]
[[4 5 6]]


In [21]:
print(arr2)
print(arr2[: , 0]) #first colum of array
print(arr2[: ,1])   #second column of an array
print(arr2[: ,2])  # third  column of an array
# 2d:[row,column]
# :-> sabhi row select karo
#0-> first column select karo

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


In [22]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(arr3.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [23]:
print(arr3[0])
print(arr3[1])
print(arr3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [24]:
print(arr3[0][2])
print(arr3[1][2])

3
6


In [25]:
print(arr3)
print(arr3[::,1:2]) #1st col value  #array[row_start:row_end , col_start:col_end] ,
#::   -> sabhi rows
#1:2  -> column index 1 se 2 ke pehle tak

print(arr3[2::,1:2])  # 2nd col value
                            #-2::   -> row index 2 se last tak
                            # -1:2   -> 2nd column
print(arr3[:,2]) #3rd col value



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]
[[8]]
[3 6 9]
