In [2]:
import numpy as np

In [3]:
#reshape array:array ke data ko same rakhte hue ushka structure change karna 
#r latter arey : 2d ya 3dko ek single(1d) me convert karna.arr

In [4]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)   # shape 1row and 6 column

[1 2 3 4 5 6]


In [5]:
reshaped = arr1.reshape(6,1)  #6 row and 1 column
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [13]:
reshaped2 = arr1.reshape(2,3)  # re shaped array from (1,6 )to (2,3)
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [15]:
#flatten array : 2d ya 3d ko ek single line (1d) convert karna.
print (reshaped2.flatten()) # fallened array from 2d dimensional (2,3) to (1,6) (1d)

[1 2 3 4 5 6]


In [8]:
#array stacking and splittind

In [9]:
#array stacking : do ya zyada array ko jodna (combine karna ). 
#type 2
#1)(vertical.stack np.vstack(a,b)))
#2)horizontal stack: np.hstack(a,b))
#array splitting: ek array ko chhote part mai todna


In [10]:
#stacking
a = np.array([1,2,3])
b = np.array([4,5,6])
stacked = np.stack((a,b))
print(stacked)

print(np.vstack((a,b)))  # vertical stacking - row wise output 2d
print(np.hstack((a,b))) # horizonatl stack - column wise  output 1d 

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [11]:
#splitting
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [16]:
hsplit = np.hsplit(c,3) #horizontal split ->input and output array are same dimention
print(hsplit)
for s in hsplit:
    print(s)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]
