In [1]:
import numpy as np

In [2]:
a = np.array([10,20,40,-30])
print(a)


[ 10  20  40 -30]


In [3]:
print(a+10)
print(a-30)
print(a*2)
print(a/10)
print(a**2)

[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]
[ 100  400 1600  900]


In [4]:
b = np.array ([1,4,9])
print(b)

[1 4 9]


In [5]:
print(np.square(b))
print(np.sqrt(b))

[ 1 16 81]
[1. 2. 3.]


In [6]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)


[1 2 3]
[4 5 6]


In [7]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [8]:
# dot product : computer the inner product of the two vector and sum the result
print (np.dot(a,b)) # dot product 4 10 18 = 32

32


In [9]:
print(a.T) # transpose : reture an array with  axes transposed


[1 2 3]


In [10]:
t = np.array([[1,2,3],
              [4,5,6]])
print(t)   # initial shape :2,3
print(t.T)  # shape after transpose: 32 row ko col ko row


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [11]:
# statistical function
a= np.array ([[1,2,3],[4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [12]:
print(np.sum(a))  # ssum of all element

21


In [13]:
print(a)
print(np.mean(a))  #average
print(np.median(a)) #middle value
print(np.std(a))  # standard deviation
print(np.min(a))  # smallest
print(np.max(a))  # largest

[[1 2 3]
 [4 5 6]]
3.5
3.5
1.707825127659933
1
6


In [14]:
a = np.array([1,5,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 5 3]
[4 5 6]


In [15]:
print(a==b) # comparing each element of array
print(np.array_equal(a,b)) # comapring complete array

[False  True False]
False


In [18]:
x = np.array ([1,2,3,4])
y = x.copy()
z=x.view()
# x[0] =200
# print(x) # x change hua
# print(y)  # same raha

#view
x[1] =300
print(x)
print(z) #original array ka refernce banata hai

[  1 300   3   4]
[  1 300   3   4]


In [24]:
sales = np.array([5000,7000,6500,8000,9000,7500])
print("total sales:",np.sum(sales))
print("highest sales:",np.max(sales))
print("lowest sales:",np.min(sales))
print("average sales:",np.mean(sales))
print("sd sales:",np.std(sales))




total sales: 43000
highest sales: 9000
lowest sales: 5000
average sales: 7166.666666666667
sd sales: 1247.2191289246473


In [28]:
a =([1,2,3,4])
print(np.mean(a))
print(np.median(a))

2.5
2.5


In [29]:
#random password number generator


In [32]:
r = np.random.randint(1000,9999,6)
print(r)

[8953 9075 2857 6674 6552 8076]


In [36]:
#matrix calculator
a =np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("addition:\n",a+b)
print("multiple:\n",a*b)

addition:
 [[ 6  8]
 [10 12]]
multiple:
 [[ 5 12]
 [21 32]]


In [37]:
#attendance system


In [39]:
a=np.array([22,25,20,24])
total_classes = 25
percentage=(a/total_classes)*100
print(percentage)

[ 88. 100.  80.  96.]


In [40]:
#business sales analytics system
#total sales ,average,highest ,lowest,monthly growth ,standard deviation,
#bonus eligibility,performance categories


In [44]:
sales = np.array([4000,7000,9000,4500,6700,4000,8000,11000,2300,5000,1000])
print("total_sum:",np.sum(sales))
print("average sales:",np.mean(sales))
print("highest sales:",np.max(sales))
print("lowest sales:",np.min(sales))
print("standard deviation sales:",np.std(sales))

total_sum: 62500
average sales: 5681.818181818182
highest sales: 11000
lowest sales: 1000
standard deviation sales: 2833.5067196988452
