In [1]:
import numpy as np


In [3]:
#broadcasting numpy ka ek powerful feature hai jo different shap array par arithmetic
#operations perform karna
#deta hai without manually repeating data.


In [4]:
#agr do array ka shape alag hai, numpy automatically smller array ko expand karke operation karta 
#rules of broadcasting 
#numpy shapes ko right to left compare karta hai:


In [8]:
a= np.array ([1,2,3,4])
b=np.array([5])
print(a+b)

[6 7 8 9]


In [9]:
#1d +2d
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])
print(arr1+arr2)

[[11 22 33]
 [14 25 36]]


In [10]:
#arr2 har row par opply hua:
#[1,2,3]+[10+20+30]
#[4,5,6]+[10+20+30]
