In [3]:
import numpy as np
#handling with non value

In [4]:
data1 = np.array([1,2,np.nan,4,np.inf])
print(data1)

[ 1.  2. nan  4. inf]


In [5]:
print(np.isnan(data1))

[False False  True False False]


In [6]:
print(np.nan_to_num(data1)) #null value ko 0 mai badlta 


[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [7]:
#save and load arrays

In [9]:
arr =np.array([1,0,0,8])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 8]


In [10]:
loaded_arr=np.load('my_array.npy')
print(loaded_arr)

[1 0 0 8]


In [11]:
# create 5x5 martrix 


In [21]:
arr=np.arange(1,26).reshape(5,5)
print("orginal matrix:\n;",arr)

orginal matrix:
; [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [18]:
arr = np.arange(1,26).reshape(5,5)
print("original matrix:\n",arr)
print("last row:\n",arr[-1])
print("first column:\n",arr[:,0])
print("3x submatrix:\n",arr[1:4,1:4])

original matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
last row:
 [21 22 23 24 25]
first column:
 [ 1  6 11 16 21]
3x3 submatrix:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]
