In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.4.4


In [4]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
import numpy as np

In [4]:
list=[1,2,3] #list
print(list)
print(type(list))


[1, 2, 3]
<class 'list'>


In [5]:
arr_list = np.array(list)
print(arr_list)  #array  1d array h!

[1 2 3]


In [6]:
print(type(arr_list))

<class 'numpy.ndarray'>


In [8]:
list1 = [1,2,3]
list2 = [4,5,6]
arr_list1 =np.array([list1,list2])
print(arr_list1) # [[1,2,3][4,5,6]]  # [[,double mtlb 2d array
print(type(arr_list1))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [10]:
# axix 0 - row upper se neeche
#axis 1 - columns baaye se daye
#2 rows
#3columns
#arr[0][0] = 1
#arr[1][2] = 6
#pahela index = row
#dusra index = column

In [14]:
list1 =[1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
arr_list2 = np.array([[list1,list2,list3]])
print(arr_list2)
print(type(arr_list2)) #3d array [[[

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


In [15]:
print(arr_list2.ndim) #  find dimensional .ndim

3


In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
