In [2]:
import numpy as np

In [4]:
list = [12,3,4]
arr =np.array(list)
print(arr.ndim)
print(arr)


1
[12  3  4]


In [6]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
print(np.zeros(2,3))

TypeError: Cannot interpret '3' as a data type